production:
  adapter: mysql2
  encoding: utf8
  database: myrails_production
  username: root
  password: passer@X86
  host: localhost
  port: 3306

development:
  adapter: mysql2
  encoding: utf8
  database: myrails_development
  username: root 
  password: passer@X86    
  host: localhost
  port: 3306

